packages:
  - 'packages/*'
  - 'examples/**/*'

catalog:
  # Build tools
  typescript: ^5.3.0
  vite: ^5.0.0
  vite-plugin-dts: ^4.5.0

  # Testing
  vitest: ^1.0.0
  jsdom: ^27.4.0

  # three.js ecosystem
  three: ^0.182.0
  '@types/three': ^0.182.0
  '@webgpu/types': ^0.1.0

  # React ecosystem
  react: ^18.2.0
  react-dom: ^18.2.0
  '@types/react': ^18.2.0
  '@react-three/fiber': ^8.15.0
  '@testing-library/react': ^16.3.1

  # Vue ecosystem
  vue: ^3.4.0
  '@tresjs/core': ^4.0.0
  '@vue/test-utils': ^2.4.6

  # Angular ecosystem
  '@angular/core': ^17.0.0
  rxjs: ^7.8.0
  zone.js: ^0.14.0

  # Linting & Formatting
  eslint: ^8.55.0
  prettier: ^3.1.0
  '@typescript-eslint/eslint-plugin': ^6.13.0
  '@typescript-eslint/parser': ^6.13.0
  eslint-config-prettier: ^9.1.0
  eslint-import-resolver-typescript: ^3.6.0
  eslint-plugin-import: ^2.29.0

  # Other dev dependencies
  '@types/node': ^20.10.0
  tsx: ^4.7.0
  typedoc: ^0.25.0
  typedoc-plugin-markdown: 3.17.1
  '@vitest/coverage-v8': ^1.0.0
  '@vercel/analytics': ^1.6.1
  vitepress: ^1.6.4
