packages:
  # Core packages
  - 'packages/core/*'
  # Host integrations
  - 'packages/hosts/*'
  # Feature addons
  - 'packages/addons/*'
  # UI packages
  - 'packages/ui/*'
  # Framework mounts
  - 'packages/mounts/*'
  # CLI & build tools
  - 'packages/tools/*'
  # Examples (coming soon)
  # - 'examples/**/*'

catalog:
  # Build tools
  typescript: ^5.9.0
  vite: ^7.3.0
  vite-plugin-dts: ^4.5.0

  # Testing
  vitest: ^4.0.0
  jsdom: ^27.4.0

  # three.js ecosystem
  three: ^0.182.0
  '@types/three': ^0.182.0
  '@webgpu/types': ^0.1.0

  # React ecosystem
  react: ^18.2.0
  react-dom: ^18.2.0
  '@types/react': ^18.2.0
  '@react-three/fiber': ^8.15.0
  '@testing-library/react': ^16.3.1

  # Vue ecosystem
  vue: ^3.4.0
  '@tresjs/core': ^4.0.0
  '@vue/test-utils': ^2.4.6

  # Angular ecosystem
  '@angular/core': ^17.0.0
  rxjs: ^7.8.0
  zone.js: ^0.14.0

  # Linting & Formatting
  oxlint: ^1.1.0
  oxfmt: ^0.23.0

  # Other dev dependencies
  '@types/node': ^25.0.0
  tsx: ^4.7.0
  typedoc: ^0.28.0
  typedoc-plugin-markdown: ^4.9.0
  '@vitest/coverage-v8': ^4.0.0
  '@vercel/analytics': ^1.6.1
  vitepress: ^1.6.4
