name: 🐛 Bug Report
description: Report a bug or unexpected behavior in 3Lens
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out this form as completely as possible.
        
        Before submitting, please search [existing issues](https://github.com/adriandarian/3Lens/issues) to avoid duplicates.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Set up scene with...
        2. Enable 3Lens overlay...
        3. Click on...
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: package
    attributes:
      label: Affected Package(s)
      description: Which 3Lens package(s) are affected?
      multiple: true
      options:
        - "@3lens/core"
        - "@3lens/overlay"
        - "@3lens/react-bridge"
        - "@3lens/angular-bridge"
        - "@3lens/vue-bridge"
        - "Other/Unknown"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: 3Lens Version
      description: What version of 3Lens are you using?
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: input
    id: three-version
    attributes:
      label: Three.js Version
      description: What version of Three.js are you using?
      placeholder: "e.g., 0.160.0"
    validations:
      required: true

  - type: dropdown
    id: renderer
    attributes:
      label: Renderer Type
      description: Which Three.js renderer are you using?
      options:
        - WebGLRenderer
        - WebGPURenderer
        - Both
        - Unknown
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser(s) are you experiencing this issue in?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: "e.g., macOS 14.0, Windows 11, Ubuntu 22.04"
    validations:
      required: true

  - type: textarea
    id: console-errors
    attributes:
      label: Console Errors
      description: If there are any console errors, please paste them here.
      placeholder: Paste any relevant console errors...
      render: shell

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: If possible, provide a minimal code sample that reproduces the issue.
      placeholder: |
        ```typescript
        import { DevtoolProbe } from '@3lens/core';
        
        // Your code here...
        ```
      render: typescript

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or screen recordings about the bug.
      placeholder: Any additional information...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have provided all required information above
          required: true
        - label: I can provide a minimal reproduction if requested
          required: false
