name: ✨ Feature Request
description: Suggest a new feature or enhancement for 3Lens
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out this form to help us understand your request.
        
        Before submitting, please search [existing issues](https://github.com/adriandarian/3Lens/issues) and [discussions](https://github.com/adriandarian/3Lens/discussions) to avoid duplicates.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "A clear and concise description of what the problem is. Ex. I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: What other approaches could solve this problem?

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area of 3Lens does this feature relate to?
      options:
        - Core functionality
        - UI/Overlay
        - Performance profiling
        - Memory/resource tracking
        - Scene inspection
        - Transform tools
        - Plugin system
        - Framework bridge (React)
        - Framework bridge (Angular)
        - Framework bridge (Vue)
        - WebGPU support
        - Documentation
        - Developer experience
        - Other
    validations:
      required: true

  - type: dropdown
    id: package
    attributes:
      label: Target Package(s)
      description: Which 3Lens package(s) would this feature affect?
      multiple: true
      options:
        - "@3lens/core"
        - "@3lens/overlay"
        - "@3lens/react-bridge"
        - "@3lens/angular-bridge"
        - "@3lens/vue-bridge"
        - "New package"
        - "Unknown/Multiple"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would improve my workflow
        - Important for my use case
        - Critical/Blocking
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe the specific use case(s) where this feature would be helpful.
      placeholder: |
        Example: When debugging a complex scene with 1000+ objects, I need to...
    validations:
      required: true

  - type: textarea
    id: api-design
    attributes:
      label: API Design (Optional)
      description: If you have ideas about the API, share them here.
      placeholder: |
        ```typescript
        // Example API usage
        probe.someNewMethod({
          option: value
        });
        ```
      render: typescript

  - type: textarea
    id: mockup
    attributes:
      label: UI/UX Mockup (Optional)
      description: If this is a UI feature, include any mockups, wireframes, or screenshots of similar features.
      placeholder: Drag and drop images or describe the UI...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help implement this feature?
      options:
        - label: I would be willing to submit a PR for this feature
          required: false
        - label: I can help test this feature when implemented
          required: false
        - label: I can provide more detailed requirements if needed
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and discussions for this feature
          required: true
        - label: This feature would benefit the broader 3Lens community
          required: true
